export const shopActions = {
  SET_SHOP_USER: 'SET_SHOP_USER',
  SET_SELECTED_SHOP: 'SET_SELECTED_SHOP',
  CLEAN_SHOP: 'CLEAN_SHOP',
  SET_SHOP_PRODUCTS: 'SET_SHOP_PRODUCTS',
  CLEAN_SHOP_PRODUCTS: 'CLEAN_SHOP_PRODUCTS',
  CLEAN_SHOP_SELECTED: 'CLEAN_SHOP_SELECTED'
}