export const productActions = {
  SET_PRODUCT_LIST: 'SET_PRODUCT_LIST',
  SET_SELECTED_PRODUCT: 'SET_SELECTED_PRODUCT',
  GET_RELATED_PRODUCTS: 'GET_RELATED_PRODUCTS',
  REMOVE_PRODUCT_SELECTED: 'REMOVE_PRODUCT_SELECTED',
  REMOVE_LIST_RELATED: 'REMOVE_LIST_RELATED',
  SET_CATEGORIES: 'SET_CATEGORIES',
  CLEAN_PRODUCT_SELECTED: 'CLEAN_PRODUCT_SELECTED'
}